module.exports = {
  accountsPage: '#account-settings',
  paymentMethod: '#payout-method',
  paymentMethodDropdown: '#payout-method option',
  paymentMethodMissing: '#payout-method option[value="MISSING"]',
  paymentMethodPaypal: '#payout-method option[value="PAYPAL"]',
  paymentMethodPayoneer: '#payout-method option[value="PAYONEER"]',
  paymentMethodSkrill: '#payout-method option[value="MONEYBOOKERS"]',
  selectedPayout: '#payout-method option[selected="selected"]',
  payoutEmail: '#payout-email',
  minimumPayout: '#minimum-payout',
  saveSetting: '#save-main',
  payoutModal: '.modal-dialog',
  payoutModalSave: '#save-modal-payout',
  saveMessage: '#settings-save-success',
  licenseRadioBtn: '.radio-inline input[value="false"]',
  payoneerOption: '#payoneer',
  payoneerConnectBtn: '#payoneer-connect-button',
  emailErr: '#account-payout-email .help-block.with-errors',
  licenseContentToNo: 'input[value = "false"]',
  imageSales: '#account-photo-sales',
  footageSales: '#account-video-sales',
  enhancedSales: '#account-enhanced-license',
  sensitiveSales: '#account-sensitive-use',
  payable_to_field: '#account-pay-to span',
  payout_email_field: '#account-payout-email input',
  payout_email_error: '#account-payout-email .help-block>ul>li',
  minimum_payout_field: '#account-min-payout input',
  minimum_payout_error: '#account-min-payout .help-block>ul>li',
  partial_save_error: '#settings-partial-save-error',
  userEmail: '#account-email-address .text-fluid>div',
  payToName: '#account-pay-to .text-fluid>span',
  payoutType: 'select[name="payout_method"]',
};
