module.exports = {
  residential_country: 'select[name="residential-country"]',
  residential_country_Af: 'select[name=\'residential-country\'] option[value = \'af\']',
  residential_line1: 'input[name="residential-line_1"]',
  residential_line1_error: 'input[name="residential-line_1"]+div>ul>li',
  residential_line2: 'input[name="residential-line_2"]',
  residential_line2_error: 'input[name="residential-line_2"]+div>ul>li',
  residential_city: 'input[name="residential-city"]',
  residential_city_error: 'input[name="residential-city"]+div>ul>li',
  residential_postal_code: 'input[name="residential-postal_code"]',
  residential_postal_code_error: 'input[name="residential-postal_code"]+div>ul>li',
  residential_province: 'input[name="residential-province"]',
  residential_province_error: 'select[name="residential-province"]+div>ul>li',
  residential_phone: 'input[name="residential-phone"]',
  residential_phone_error: 'input[name="residential-phone"]+div>ul>li',
  checkbox: 'input[type="checkbox"]',
  payment_country: 'select[name="payment-country"]',
  payment_line1: 'input[name="payment-line_1"]',
  payment_line1_error: 'input[name="payment-line_1"]+div>ul>li',
  payment_line2: 'input[name="payment-line_2"]',
  payment_line2_error: 'input[name="payment-line_2"]+div>ul>li',
  payment_city: 'input[name="payment-city"]',
  payment_city_error: 'input[name="payment-city"]+div>ul>li',
  payment_postal_code: 'input[name="payment-postal_code"]',
  payment_postal_code_error: 'input[name="payment-postal_code"]+div>ul>li',
  payment_province: 'input[name="payment-province"]',
  payment_province_error: 'select[name="payment-province"]+div>ul>li',
  saveAddressBtn: 'button[type=\'submit\']',
  addressUpdateMsg: '#address-scheduled',
  addressUpdated: '#address-updated',
};
