module.exports = {
  dashboard: '.lihp-page',
  uploadImgBtn: '#upload-images',
  uploadDropdownBtn: '.btn-primary .glyphicon-menu-down',
  uploadVidBtn: 'ul.dropdown-menu:nth-child(3) > li:nth-child(1) > a:nth-child(1)',
  topPerfContainer: '#top-earners-container',
  topPerfEarnings: '[id *=top5-earners-row-earnings]',
  selectSets: '#select-sets-button',
  addSetsModal: '.modal-content',
  clearSetBtn: 'a.pull-right',
  applyBtn: '#btn-apply',
  selectedSetsOnDashboard: '[id*=set-display-] .thumbnail-letterbox',
  setTypeOnModal: '#trackYourSets>tbody>tr select[data-test-ref="set-type-selector"]',
  selectSetOnModal: 'select[data-test-ref= "set-selector"]',
  addSet: 'td.set-name.text-left',
  setOverview: '#track-sets-container',
  announcementHyperlinks: '.hidden-xs .announcement-link',
  announcementTime: '.announcement-time',
  announcementTitle: '.hidden-xs #announcements-container>a',
  addResources: '.hidden-xs #resources-blog-container>a',
  resourcesHyperlink: '.hidden-xs .blog-post-container',
  resourcesViewMore: '.hidden-xs #resources-blog-container>div:nth-child(3)>a',
  unpaidEarningsSection: 'div.hidden-xs:nth-child(2) > div:nth-child(1) > div',
  unpaidEarningsTitle: 'div.hidden-xs:nth-child(2) #unpaid-earnings',
  unpaidEarnings: 'div.hidden-xs:nth-child(2) .unpaid-earnings-module-value',
  learnMore: 'div.hidden-xs:nth-child(2) a.inline-block',
  contentStatusThumb: 'div:nth-child(1) > div:nth-child(6) > div:nth-child(1) a',
  earningsSummaryContainer: '#earnings-summary-container',
  earningsOfMediaType: 'select[name=\'mediaType\']',
  totalEarnings: '.earnings-summary-earnings>div',
  totalDownloads: '.earnings-summary-downloads>div',
  earningSummaryGraphSection: '#earnings-summary-graph',
};
