module.exports = {
  earningsSummary: '#earnings-container',
  currentYear: 'select[name= "year"] option[selected = "selected"]',
  totalDownloads: 'table>thead>tr:nth-child(3)>th:nth-child(2)',
  totalEarnings: 'table>thead>tr:nth-child(3)>th:nth-child(3)',
  paymentHistoryLink: '.pull-right>a:first-child',
  totalDates: 'tr.earnings-day',
  showLessDates: '.toggle-earnings-less',
  showAllDates: '.toggle-earnings-all',
  msgOnBottom: '.alert-general',
  downloadSpreadsheetBtn: '#download-earnings-form-button',
  spreadSheetModal: '#earnings-downloads-modal .modal-dialog',
  startDate: 'input[name="start_date"]',
  endDate: 'input[name="end_date"]',
  spreadsheetDownloadBtn: '#save-modal-downloads',
  modalCancelBtn: '.modal-footer .btn-default',
  subscriptionTab: '.nav-tabs>li:nth-child(2)',
  enhancedTab: '.nav-tabs>li:nth-child(3)',
  onDemandTab: '.nav-tabs>li:nth-child(4)',
  videoTab: '.nav-tabs>li:nth-child(5)',
  singleAndOthersTab: '.nav-tabs>li:nth-child(6)',
};
