module.exports = {
  newbieOverlay: '.o_Dialog_Dialog_mainContentContainer',
  newContributorDialogStartBtn: 'button.o_EditorWelcomeDialog_EditorWelcomeDialog_button',
  allContentCards: 'div[data-react-toolbox=\'card\']',
  contentCheckBox: '.o_Checkbox_Checkbox_check',
  contentMenuThreeDots: 'span[data-test-ref="content-menu"]>button>span',
  contentMenuDropdown: '.o_Menu_Menu_active',
  contentMenuDelete: 'span[data-test-ref=\'card-action-menu-delete\']>li>span',
  confirmDeleteDialog: '.o_EditorDeleteConfirmDialog_EditorDeleteConfirmDialog_dialog',
  contentDeleteConfirmButton: 'span[data-test-ref=\'delete-content-confirm\']',
  descriptionTextInput: 'textarea[name="description"]',
  descriptionPlaceHolder: 'span[data-test-ref="description-text-input"] label[class="o_input_theme_label o_Input_Input_label"]',
  categoryDropdown: '[data-test-ref="category-dropdown-one"] input',
  categoryDropdownSection: 'span[data-test-ref=\'category-dropdown-one\'] ul.o_EditorCategory_EditorCategory_values',
  categoryArts: 'span[data-test-ref=\'category-dropdown-one\'] ul>li:nth-child(4)>label',
  submitBtn: 'span[data-test-ref="submit-button"] button',
  newbieSubmitOverlay: '.o_Dialog_Dialog_mainContentContainer',
  navTab: '.o_Tabs_Tabs_navigation',
  submitMore: '.o_EditorNewbieSubmitThankYouDialog_EditorNewbieSubmitThankYouDialog_buttonGroup>button',
  alertMsg: '.o_EditorErrorBar_EditorErrorBar_alertMessage',
  enterKeywords: '.o_EditorMain_EditorMain_editorSidebar input[name="pendingKeywords"]',
  deletePendingMedia: 'span[data-test-ref="delete-button"]>button',
  deleteModal: '.o_EditorDeleteConfirmDialog_EditorDeleteConfirmDialog_mainContentContainer',
  deleteConfirmBtn: 'span[data-test-ref="delete-content-confirm"]>button',
  locationInput: 'input[name="location"]',
  locationSelector: '.o_EditorAutocomplete_EditorAutocomplete_autocomplete',
};
