module.exports = {
  newbieOverlay: '.o_Dialog_Dialog_mainContentContainer',
  newContributorDialogStartBtn: 'button.o_EditorWelcomeDialog_EditorWelcomeDialog_button',
  keywordTool: 'span[data-icon="blog"]',
  keywordToolBody: '.o_KeywordTool_KeywordTool_bottomSheetBody',
  search: '.o_KeywordTool_KeywordTool_searchInputElement',
  searchBtn: '.o_KeywordTool_KeywordTool_searchButton',
  searchResult: '.o_KeywordTool_KeywordTool_searchResults',
  resultCheckbox: '.o_KeywordToolCard_KeywordToolCard_checkboxHidden',
  selectionMsg: '.o_KeywordToolZeroState_KeywordToolZeroState_zeroStateTitle',
  keywordPill: '.o_Pill_Pill_filterPill',
  addSuggestedKeywords: 'button[data-test-ref="keyword-tool-add-all-button"]',
  addedKeywordPills: '.o_KeywordTool_KeywordTool_panel .o_EditorKeywords_Keyword_filterText',
  copyKeyword: '.o_KeywordTool_KeywordTool_keywordToolCopyButton',
  keywordToolCloseBtn: '.o_KeywordTool_KeywordTool_right>button>span',
  toSubmitImages: '.o_EditorCard_EditorCard_editorCardMediaHolder',
  toSubmitImagesCheckBox: '.o_checkbox_theme_field.o_Checkbox_Checkbox_field',
  keywordContainerEditPage: '.o_EditorKeywords_EditorKeywords_keywordsContainer',
  keywordContainerOptions: '.o_EditorKeywords_EditorKeywords_keywordsContainer span[data-test-ref="keywords-more-menu"]>button',
  keywordMenu: '.o_Menu_Menu_active',
  editKeywordPills: '.o_EditorSidebar_EditorSidebar_rightArea .o_EditorKeywords_EditorKeywords_attachedKeywords .o_Pill_Pill_filterText',
  editSaveBtn: '.o_Button_Button_stacked span[data-icon="save"]',
  clearKeywordsTool: '.o_KeywordTool_KeywordTool_keywordToolClearButton',
  keywordToolAttachBtn: 'button[data-test-ref="keyword-tool-attach-button"]',
  editPage: '.o_EditorSidebar_EditorSidebar_rightArea',
};
