module.exports = {
  elements: {
    impHref: {
      blog: 'span[data-test-ref="header-primary-blog"]>a',
      supportCentre: 'span[data-test-ref="header-primary-support-center"]>a',
      sstkLogo: '.o_app_SiteHeader_menu>a',
      logIn: '.o_app_Header_loginButton',
      signUp: '.o_app_Header_joinButton',
      getStarted: '.o_Button_Button_primary.o_Button_Button_large',
      joinNow: '.o_Storytelling_Storytelling_container>div:nth-child(1) .o_Button_Button_buttonWithRipple',
      globalEarnings: '.o_Storytelling_Storytelling_container>div:nth-child(2) .o_Button_Button_buttonWithRipple',
      exploreTools: '.o_Storytelling_Storytelling_container>div:nth-child(3) .o_Button_Button_buttonWithRipple',
      joinNowStory4: '.o_Storytelling_Storytelling_container>div:nth-last-child(2) .o_Button_Button_buttonWithRipple',
      learnMore: '.o_Storytelling_Storytelling_container>div:last-child .o_Button_Button_buttonWithRipple',
      shotList: '.o_ContentCardGrid_ContentCardGrid_inner-container>div:nth-child(1)>a',
      videoWorkshops: '.o_ContentCardGrid_ContentCardGrid_inner-container>div:nth-child(2)>a',
      ctrbBlog: '.o_ContentCardGrid_ContentCardGrid_inner-container>div:nth-child(3)>a',
      joinNowBottom: '.o_Button_Button_blockLevel',
      signInBottom: '.o_HomepageSignup_HomepageSignup_darkLink',
    },
    impText: {
      heading: '.o_HomepageHero_HomepageHero_title',
      subHeading: '.o_HomepageHero_HomepageHero_subtitle',
      subTitle: '.o_LOHP_LOHP_subtitle',
      sellingPoint1: '.o_LOHP_LOHP_selling-points .o_FlexGrid_flexboxgrid_row div.o_SellingPoints_SellingPoints_container:nth-child(1) p+p',
      sellingPoint2: '.o_LOHP_LOHP_selling-points .o_FlexGrid_flexboxgrid_row div.o_SellingPoints_SellingPoints_container:nth-child(2) p+p',
      sellingPoint3: '.o_LOHP_LOHP_selling-points .o_FlexGrid_flexboxgrid_row div.o_SellingPoints_SellingPoints_container:nth-child(3) p+p',
      sellingPoint4: '.o_LOHP_LOHP_selling-points .o_FlexGrid_flexboxgrid_row div.o_SellingPoints_SellingPoints_container:nth-child(4) p+p',
      storyText1: '.o_Storytelling_Storytelling_container>div:nth-child(1) .o_Storytelling_Storytelling_title',
      storyText2: '.o_Storytelling_Storytelling_container>div:nth-child(2) .o_Storytelling_Storytelling_title',
      storyText3: '.o_Storytelling_Storytelling_container>div:nth-child(3) .o_Storytelling_Storytelling_title',
      storyText4: '.o_Storytelling_Storytelling_container>div:nth-last-child(2) .o_Storytelling_Storytelling_title',
      storyText5: '.o_Storytelling_Storytelling_container>div:last-child .o_Storytelling_Storytelling_title',
    },
  },
};
