module.exports = {
  portfolioForm: '#information-form',
  viewPortfolioBtn: 'a.btn-primary',
  displayName: '#display-name',
  displayNameErr: '.help-block>ul>li',
  portfolioValidationErr: '.with-errors>ul>li',
  portfolioNote: 'p.text-small',
  portfolioUrl: '#vanity-url-username',
  contributorBio: '#long_bio',
  contributorTagline: '#bio',
  contributorLocation: '#location-selectized',
  locationIndia: 'div [data-value= \'in\']',
  contributorWebsite: '#website',
  saveBtn: '.btn-primary.btn-lg',
  saveSuccessMsg: 'div.alert:nth-child(3)',
  saveErrorMsg: 'div.alert.alert-danger:nth-child(3)',
  contributorType: '#contributor-type-list-selectized',
  contributorTypeDropdown: '.selectize-dropdown-content>div',
  styleList: '#style-list-selectized',
  styleDropdown: 'div.optgroup:nth-child(1) .option',
  subjectList: '#subject-matter-list-selectized',
  equipmentList: '#equipment-list-selectized',
  uploadPhoto: '#upload-photo-submit',
  deletePhoto: '#delete-photo-submit',
  deleteConfirm: '#delete-confirm',
  photoUpdateSucess: '#photo-update-success',
  setContainer: '#sets-container>li',
};
