module.exports = {
  submitNewForm: '.info.mrg-b-lrg a',
  questionnaire: '#questionnaire',
  submitBtn: 'button[type = "submit"]',
  formApproval: '#approval-date',
  yesBtn: 'input[value = "YES"]',
  taxQuestion3: '#question3',
  w9TaxForm: '#tax-form',
  w9PayeeName: '#payee_name',
  w9Individual: 'input[value="individual"]',
  w9SSN: '#ssn',
  w9SignDate: '#sign_date',
  eSignature: '#esignature',
  w8Form: 'h1[data-test-ref="heading"]',
  w8PayeeName: '#payee-name',
  w8Citizenship: '#payee-citizenship',
  w8SSN: '#payee-ssn',
  w8SsnNumber: '#tax-identification-number',
  w8ResidentialPOBoxNo: '#permanent-is-not-po-or-co',
  w8PayeeBirthday: '#payee-birthday',
  w8Under18ErrMsg: '#invalid-birthday',
  w8PayeeCountry: '#payee-treaty-country',
  w8Preview: '#pdf-preview',
  otherTaxForms: '.alert.alert-warning',
  formRejected: '#form-rejected',
  formExpired: '#form-expired',
  formPending: '#form-pending',
};
